package burl.es.orderbook.model.order;

import lombok.Data;

@Data
public class OrderSnapshot {

//	timestamp 	The time when this message was generated by the market, as milliseconds since midnight.
//	A 			literal string identifying this as an "Add Order to Book" message.
//			order-id 	A unique string that subsequent "Reduce Order" messages will use to modify this order.
//	side 		A 'B' if this is a buy order (a bid), and a 'S' if this is a sell order (an ask).
//	price 		The limit price of this order.
//	size 		The size in shares of this order, when it was initially sent to the market by some stock trader.

	final long timestamp;
	final String orderId;
	final Side side;
	final String price;
	final String size;
}
